version: "2"
linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - gocritic
    - misspell
    - nilerr
    - revive
    - unconvert
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
    gocritic:
      disabled-checks:
        - ifElseChain
formatters:
  enable:
    - gofmt
    - goimports
