-- Row-level security on Postgres (docs/specs/16-organizations.md#isolation),
-- defense in depth behind the service layer's filters. Every tenant table
-- gets org_id (tables under a repo, revision, thread… take it from their
-- parent through a trigger, so inserts don't change) and a policy: a session
-- whose app.org_id is set sees and writes only that org's rows (and shared
-- rows with no org); an unset or empty app.org_id sees everything. FORCE
-- applies the policies to the tables' owner too; superusers still bypass
-- them, so production connects as an ordinary role. SQLite relies on the
-- service layer.
-- +postgres
CREATE FUNCTION kmdn_org_visible(o TEXT) RETURNS BOOLEAN LANGUAGE sql STABLE AS $$ SELECT o IS NULL OR COALESCE(current_setting('app.org_id', true), '') IN ('', o) $$;


-- Rows under repos.
CREATE FUNCTION kmdn_org_from_repos_repo_id() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.org_id := (SELECT org_id FROM repos WHERE id = NEW.repo_id); RETURN NEW; END $$;
ALTER TABLE revisions ADD COLUMN org_id TEXT;
UPDATE revisions SET org_id = p.org_id FROM repos p WHERE p.id = revisions.repo_id;
ALTER TABLE revisions ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER revisions_org BEFORE INSERT OR UPDATE OF repo_id ON revisions FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_repos_repo_id();
ALTER TABLE threads ADD COLUMN org_id TEXT;
UPDATE threads SET org_id = p.org_id FROM repos p WHERE p.id = threads.repo_id;
ALTER TABLE threads ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER threads_org BEFORE INSERT OR UPDATE OF repo_id ON threads FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_repos_repo_id();
ALTER TABLE repo_hooks ADD COLUMN org_id TEXT;
UPDATE repo_hooks SET org_id = p.org_id FROM repos p WHERE p.id = repo_hooks.repo_id;
ALTER TABLE repo_hooks ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER repo_hooks_org BEFORE INSERT OR UPDATE OF repo_id ON repo_hooks FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_repos_repo_id();
ALTER TABLE repo_members ADD COLUMN org_id TEXT;
UPDATE repo_members SET org_id = p.org_id FROM repos p WHERE p.id = repo_members.repo_id;
ALTER TABLE repo_members ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER repo_members_org BEFORE INSERT OR UPDATE OF repo_id ON repo_members FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_repos_repo_id();
ALTER TABLE agent_key_repos ADD COLUMN org_id TEXT;
UPDATE agent_key_repos SET org_id = p.org_id FROM repos p WHERE p.id = agent_key_repos.repo_id;
ALTER TABLE agent_key_repos ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER agent_key_repos_org BEFORE INSERT OR UPDATE OF repo_id ON agent_key_repos FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_repos_repo_id();
ALTER TABLE change_summaries ADD COLUMN org_id TEXT;
UPDATE change_summaries SET org_id = p.org_id FROM repos p WHERE p.id = change_summaries.repo_id;
ALTER TABLE change_summaries ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER change_summaries_org BEFORE INSERT OR UPDATE OF repo_id ON change_summaries FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_repos_repo_id();
ALTER TABLE consistency_findings ADD COLUMN org_id TEXT;
UPDATE consistency_findings SET org_id = p.org_id FROM repos p WHERE p.id = consistency_findings.repo_id;
ALTER TABLE consistency_findings ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER consistency_findings_org BEFORE INSERT OR UPDATE OF repo_id ON consistency_findings FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_repos_repo_id();
ALTER TABLE consistency_ignores ADD COLUMN org_id TEXT;
UPDATE consistency_ignores SET org_id = p.org_id FROM repos p WHERE p.id = consistency_ignores.repo_id;
ALTER TABLE consistency_ignores ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER consistency_ignores_org BEFORE INSERT OR UPDATE OF repo_id ON consistency_ignores FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_repos_repo_id();
ALTER TABLE consistency_judgments ADD COLUMN org_id TEXT;
UPDATE consistency_judgments SET org_id = p.org_id FROM repos p WHERE p.id = consistency_judgments.repo_id;
ALTER TABLE consistency_judgments ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER consistency_judgments_org BEFORE INSERT OR UPDATE OF repo_id ON consistency_judgments FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_repos_repo_id();
ALTER TABLE consistency_scans ADD COLUMN org_id TEXT;
UPDATE consistency_scans SET org_id = p.org_id FROM repos p WHERE p.id = consistency_scans.repo_id;
ALTER TABLE consistency_scans ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER consistency_scans_org BEFORE INSERT OR UPDATE OF repo_id ON consistency_scans FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_repos_repo_id();
ALTER TABLE follows ADD COLUMN org_id TEXT;
UPDATE follows SET org_id = p.org_id FROM repos p WHERE p.id = follows.repo_id;
ALTER TABLE follows ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER follows_org BEFORE INSERT OR UPDATE OF repo_id ON follows FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_repos_repo_id();
ALTER TABLE link_sources ADD COLUMN org_id TEXT;
UPDATE link_sources SET org_id = p.org_id FROM repos p WHERE p.id = link_sources.repo_id;
ALTER TABLE link_sources ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER link_sources_org BEFORE INSERT OR UPDATE OF repo_id ON link_sources FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_repos_repo_id();
ALTER TABLE links ADD COLUMN org_id TEXT;
UPDATE links SET org_id = p.org_id FROM repos p WHERE p.id = links.repo_id;
ALTER TABLE links ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER links_org BEFORE INSERT OR UPDATE OF repo_id ON links FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_repos_repo_id();
ALTER TABLE page_reads ADD COLUMN org_id TEXT;
UPDATE page_reads SET org_id = p.org_id FROM repos p WHERE p.id = page_reads.repo_id;
ALTER TABLE page_reads ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER page_reads_org BEFORE INSERT OR UPDATE OF repo_id ON page_reads FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_repos_repo_id();
ALTER TABLE passage_files ADD COLUMN org_id TEXT;
UPDATE passage_files SET org_id = p.org_id FROM repos p WHERE p.id = passage_files.repo_id;
ALTER TABLE passage_files ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER passage_files_org BEFORE INSERT OR UPDATE OF repo_id ON passage_files FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_repos_repo_id();
ALTER TABLE passages ADD COLUMN org_id TEXT;
UPDATE passages SET org_id = p.org_id FROM repos p WHERE p.id = passages.repo_id;
ALTER TABLE passages ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER passages_org BEFORE INSERT OR UPDATE OF repo_id ON passages FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_repos_repo_id();
ALTER TABLE search_docs ADD COLUMN org_id TEXT;
UPDATE search_docs SET org_id = p.org_id FROM repos p WHERE p.id = search_docs.repo_id;
ALTER TABLE search_docs ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER search_docs_org BEFORE INSERT OR UPDATE OF repo_id ON search_docs FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_repos_repo_id();

-- Rows under revisions.
CREATE FUNCTION kmdn_org_from_revisions_revision_id() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.org_id := (SELECT org_id FROM revisions WHERE id = NEW.revision_id); RETURN NEW; END $$;
ALTER TABLE approvals ADD COLUMN org_id TEXT;
UPDATE approvals SET org_id = p.org_id FROM revisions p WHERE p.id = approvals.revision_id;
ALTER TABLE approvals ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER approvals_org BEFORE INSERT OR UPDATE OF revision_id ON approvals FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_revisions_revision_id();
ALTER TABLE review_summaries ADD COLUMN org_id TEXT;
UPDATE review_summaries SET org_id = p.org_id FROM revisions p WHERE p.id = review_summaries.revision_id;
ALTER TABLE review_summaries ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER review_summaries_org BEFORE INSERT OR UPDATE OF revision_id ON review_summaries FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_revisions_revision_id();
ALTER TABLE revision_assets ADD COLUMN org_id TEXT;
UPDATE revision_assets SET org_id = p.org_id FROM revisions p WHERE p.id = revision_assets.revision_id;
ALTER TABLE revision_assets ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER revision_assets_org BEFORE INSERT OR UPDATE OF revision_id ON revision_assets FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_revisions_revision_id();
ALTER TABLE revision_checkpoints ADD COLUMN org_id TEXT;
UPDATE revision_checkpoints SET org_id = p.org_id FROM revisions p WHERE p.id = revision_checkpoints.revision_id;
ALTER TABLE revision_checkpoints ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER revision_checkpoints_org BEFORE INSERT OR UPDATE OF revision_id ON revision_checkpoints FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_revisions_revision_id();
ALTER TABLE revision_events ADD COLUMN org_id TEXT;
UPDATE revision_events SET org_id = p.org_id FROM revisions p WHERE p.id = revision_events.revision_id;
ALTER TABLE revision_events ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER revision_events_org BEFORE INSERT OR UPDATE OF revision_id ON revision_events FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_revisions_revision_id();
ALTER TABLE revision_files ADD COLUMN org_id TEXT;
UPDATE revision_files SET org_id = p.org_id FROM revisions p WHERE p.id = revision_files.revision_id;
ALTER TABLE revision_files ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER revision_files_org BEFORE INSERT OR UPDATE OF revision_id ON revision_files FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_revisions_revision_id();
ALTER TABLE revision_members ADD COLUMN org_id TEXT;
UPDATE revision_members SET org_id = p.org_id FROM revisions p WHERE p.id = revision_members.revision_id;
ALTER TABLE revision_members ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER revision_members_org BEFORE INSERT OR UPDATE OF revision_id ON revision_members FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_revisions_revision_id();
ALTER TABLE revision_publish_claims ADD COLUMN org_id TEXT;
UPDATE revision_publish_claims SET org_id = p.org_id FROM revisions p WHERE p.id = revision_publish_claims.revision_id;
ALTER TABLE revision_publish_claims ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER revision_publish_claims_org BEFORE INSERT OR UPDATE OF revision_id ON revision_publish_claims FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_revisions_revision_id();
ALTER TABLE revision_reviewers ADD COLUMN org_id TEXT;
UPDATE revision_reviewers SET org_id = p.org_id FROM revisions p WHERE p.id = revision_reviewers.revision_id;
ALTER TABLE revision_reviewers ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER revision_reviewers_org BEFORE INSERT OR UPDATE OF revision_id ON revision_reviewers FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_revisions_revision_id();
ALTER TABLE revision_save_intents ADD COLUMN org_id TEXT;
UPDATE revision_save_intents SET org_id = p.org_id FROM revisions p WHERE p.id = revision_save_intents.revision_id;
ALTER TABLE revision_save_intents ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER revision_save_intents_org BEFORE INSERT OR UPDATE OF revision_id ON revision_save_intents FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_revisions_revision_id();
ALTER TABLE revision_updates ADD COLUMN org_id TEXT;
UPDATE revision_updates SET org_id = p.org_id FROM revisions p WHERE p.id = revision_updates.revision_id;
ALTER TABLE revision_updates ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER revision_updates_org BEFORE INSERT OR UPDATE OF revision_id ON revision_updates FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_revisions_revision_id();
ALTER TABLE ydocs ADD COLUMN org_id TEXT;
UPDATE ydocs SET org_id = p.org_id FROM revisions p WHERE p.id = ydocs.revision_id;
ALTER TABLE ydocs ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER ydocs_org BEFORE INSERT OR UPDATE OF revision_id ON ydocs FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_revisions_revision_id();

-- Rows under threads.
CREATE FUNCTION kmdn_org_from_threads_thread_id() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.org_id := (SELECT org_id FROM threads WHERE id = NEW.thread_id); RETURN NEW; END $$;
ALTER TABLE comments ADD COLUMN org_id TEXT;
UPDATE comments SET org_id = p.org_id FROM threads p WHERE p.id = comments.thread_id;
ALTER TABLE comments ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER comments_org BEFORE INSERT OR UPDATE OF thread_id ON comments FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_threads_thread_id();

-- Rows under comments.
CREATE FUNCTION kmdn_org_from_comments_comment_id() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.org_id := (SELECT org_id FROM comments WHERE id = NEW.comment_id); RETURN NEW; END $$;
ALTER TABLE reactions ADD COLUMN org_id TEXT;
UPDATE reactions SET org_id = p.org_id FROM comments p WHERE p.id = reactions.comment_id;
ALTER TABLE reactions ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER reactions_org BEFORE INSERT OR UPDATE OF comment_id ON reactions FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_comments_comment_id();

-- Rows under assistant_threads.
CREATE FUNCTION kmdn_org_from_assistant_threads_thread_id() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.org_id := (SELECT org_id FROM assistant_threads WHERE id = NEW.thread_id); RETURN NEW; END $$;
ALTER TABLE assistant_messages ADD COLUMN org_id TEXT;
UPDATE assistant_messages SET org_id = p.org_id FROM assistant_threads p WHERE p.id = assistant_messages.thread_id;
ALTER TABLE assistant_messages ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER assistant_messages_org BEFORE INSERT OR UPDATE OF thread_id ON assistant_messages FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_assistant_threads_thread_id();

-- Rows under agent_keys.
CREATE FUNCTION kmdn_org_from_agent_keys_key_id() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.org_id := (SELECT org_id FROM agent_keys WHERE id = NEW.key_id); RETURN NEW; END $$;
ALTER TABLE agent_key_usage ADD COLUMN org_id TEXT;
UPDATE agent_key_usage SET org_id = p.org_id FROM agent_keys p WHERE p.id = agent_key_usage.key_id;
ALTER TABLE agent_key_usage ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER agent_key_usage_org BEFORE INSERT OR UPDATE OF key_id ON agent_key_usage FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_agent_keys_key_id();

-- Rows under repo_hooks.
CREATE FUNCTION kmdn_org_from_repo_hooks_hook_id() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.org_id := (SELECT org_id FROM repo_hooks WHERE id = NEW.hook_id); RETURN NEW; END $$;
ALTER TABLE hook_deliveries ADD COLUMN org_id TEXT;
UPDATE hook_deliveries SET org_id = p.org_id FROM repo_hooks p WHERE p.id = hook_deliveries.hook_id;
ALTER TABLE hook_deliveries ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER hook_deliveries_org BEFORE INSERT OR UPDATE OF hook_id ON hook_deliveries FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_repo_hooks_hook_id();

-- Rows under revision_checkpoints.
CREATE FUNCTION kmdn_org_from_revision_checkpoints_checkpoint_id() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.org_id := (SELECT org_id FROM revision_checkpoints WHERE id = NEW.checkpoint_id); RETURN NEW; END $$;
ALTER TABLE revision_checkpoint_files ADD COLUMN org_id TEXT;
UPDATE revision_checkpoint_files SET org_id = p.org_id FROM revision_checkpoints p WHERE p.id = revision_checkpoint_files.checkpoint_id;
ALTER TABLE revision_checkpoint_files ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER revision_checkpoint_files_org BEFORE INSERT OR UPDATE OF checkpoint_id ON revision_checkpoint_files FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_revision_checkpoints_checkpoint_id();

-- Rows under revision_updates.
CREATE FUNCTION kmdn_org_from_revision_updates_update_id() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.org_id := (SELECT org_id FROM revision_updates WHERE id = NEW.update_id); RETURN NEW; END $$;
ALTER TABLE revision_update_files ADD COLUMN org_id TEXT;
UPDATE revision_update_files SET org_id = p.org_id FROM revision_updates p WHERE p.id = revision_update_files.update_id;
ALTER TABLE revision_update_files ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER revision_update_files_org BEFORE INSERT OR UPDATE OF update_id ON revision_update_files FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_revision_updates_update_id();

-- Rows under ydocs.
CREATE FUNCTION kmdn_org_from_ydocs_ydoc_id() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.org_id := (SELECT org_id FROM ydocs WHERE id = NEW.ydoc_id); RETURN NEW; END $$;
ALTER TABLE ydoc_snapshots ADD COLUMN org_id TEXT;
UPDATE ydoc_snapshots SET org_id = p.org_id FROM ydocs p WHERE p.id = ydoc_snapshots.ydoc_id;
ALTER TABLE ydoc_snapshots ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER ydoc_snapshots_org BEFORE INSERT OR UPDATE OF ydoc_id ON ydoc_snapshots FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_ydocs_ydoc_id();
ALTER TABLE ydoc_updates ADD COLUMN org_id TEXT;
UPDATE ydoc_updates SET org_id = p.org_id FROM ydocs p WHERE p.id = ydoc_updates.ydoc_id;
ALTER TABLE ydoc_updates ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER ydoc_updates_org BEFORE INSERT OR UPDATE OF ydoc_id ON ydoc_updates FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_ydocs_ydoc_id();
ALTER TABLE ydoc_clients ADD COLUMN org_id TEXT;
UPDATE ydoc_clients SET org_id = p.org_id FROM ydocs p WHERE p.id = ydoc_clients.ydoc_id;
ALTER TABLE ydoc_clients ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER ydoc_clients_org BEFORE INSERT OR UPDATE OF ydoc_id ON ydoc_clients FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_ydocs_ydoc_id();

-- Rows under groups.
CREATE FUNCTION kmdn_org_from_groups_group_id() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.org_id := (SELECT org_id FROM groups WHERE id = NEW.group_id); RETURN NEW; END $$;
ALTER TABLE group_members ADD COLUMN org_id TEXT;
UPDATE group_members SET org_id = p.org_id FROM groups p WHERE p.id = group_members.group_id;
ALTER TABLE group_members ALTER COLUMN org_id SET NOT NULL;
CREATE TRIGGER group_members_org BEFORE INSERT OR UPDATE OF group_id ON group_members FOR EACH ROW EXECUTE FUNCTION kmdn_org_from_groups_group_id();

-- The policies.
ALTER TABLE orgs ENABLE ROW LEVEL SECURITY;
ALTER TABLE orgs FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON orgs USING (kmdn_org_visible(id)) WITH CHECK (kmdn_org_visible(id));
ALTER TABLE agent_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_keys FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON agent_keys USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE assistant_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE assistant_threads FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON assistant_threads USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE groups FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON groups USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE install_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE install_claims FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON install_claims USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE invites FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON invites USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON notifications USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE org_domains ENABLE ROW LEVEL SECURITY;
ALTER TABLE org_domains FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON org_domains USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE org_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE org_keys FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON org_keys USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE org_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE org_members FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON org_members USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE org_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE org_settings FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON org_settings USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE repos ENABLE ROW LEVEL SECURITY;
ALTER TABLE repos FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON repos USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE uploads ENABLE ROW LEVEL SECURITY;
ALTER TABLE uploads FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON uploads USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE assistant_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE assistant_runs FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON assistant_runs USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON audit_log USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE forge_hosts ENABLE ROW LEVEL SECURITY;
ALTER TABLE forge_hosts FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON forge_hosts USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE jobs FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON jobs USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE secrets ENABLE ROW LEVEL SECURITY;
ALTER TABLE secrets FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON secrets USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE webhook_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_deliveries FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON webhook_deliveries USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE revisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE revisions FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON revisions USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE threads FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON threads USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE repo_hooks ENABLE ROW LEVEL SECURITY;
ALTER TABLE repo_hooks FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON repo_hooks USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE repo_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE repo_members FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON repo_members USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE agent_key_repos ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_key_repos FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON agent_key_repos USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE change_summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE change_summaries FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON change_summaries USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE consistency_findings ENABLE ROW LEVEL SECURITY;
ALTER TABLE consistency_findings FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON consistency_findings USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE consistency_ignores ENABLE ROW LEVEL SECURITY;
ALTER TABLE consistency_ignores FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON consistency_ignores USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE consistency_judgments ENABLE ROW LEVEL SECURITY;
ALTER TABLE consistency_judgments FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON consistency_judgments USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE consistency_scans ENABLE ROW LEVEL SECURITY;
ALTER TABLE consistency_scans FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON consistency_scans USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE follows ENABLE ROW LEVEL SECURITY;
ALTER TABLE follows FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON follows USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE link_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE link_sources FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON link_sources USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE links ENABLE ROW LEVEL SECURITY;
ALTER TABLE links FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON links USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE page_reads ENABLE ROW LEVEL SECURITY;
ALTER TABLE page_reads FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON page_reads USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE passage_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE passage_files FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON passage_files USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE passages ENABLE ROW LEVEL SECURITY;
ALTER TABLE passages FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON passages USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE search_docs ENABLE ROW LEVEL SECURITY;
ALTER TABLE search_docs FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON search_docs USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE approvals FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON approvals USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE review_summaries ENABLE ROW LEVEL SECURITY;
ALTER TABLE review_summaries FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON review_summaries USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE revision_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE revision_assets FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON revision_assets USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE revision_checkpoints ENABLE ROW LEVEL SECURITY;
ALTER TABLE revision_checkpoints FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON revision_checkpoints USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE revision_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE revision_events FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON revision_events USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE revision_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE revision_files FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON revision_files USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE revision_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE revision_members FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON revision_members USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE revision_publish_claims ENABLE ROW LEVEL SECURITY;
ALTER TABLE revision_publish_claims FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON revision_publish_claims USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE revision_reviewers ENABLE ROW LEVEL SECURITY;
ALTER TABLE revision_reviewers FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON revision_reviewers USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE revision_save_intents ENABLE ROW LEVEL SECURITY;
ALTER TABLE revision_save_intents FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON revision_save_intents USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE revision_updates ENABLE ROW LEVEL SECURITY;
ALTER TABLE revision_updates FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON revision_updates USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE ydocs ENABLE ROW LEVEL SECURITY;
ALTER TABLE ydocs FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON ydocs USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON comments USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE reactions FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON reactions USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE assistant_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE assistant_messages FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON assistant_messages USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE agent_key_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_key_usage FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON agent_key_usage USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE hook_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE hook_deliveries FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON hook_deliveries USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE revision_checkpoint_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE revision_checkpoint_files FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON revision_checkpoint_files USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE revision_update_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE revision_update_files FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON revision_update_files USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE ydoc_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE ydoc_snapshots FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON ydoc_snapshots USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE ydoc_updates ENABLE ROW LEVEL SECURITY;
ALTER TABLE ydoc_updates FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON ydoc_updates USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE ydoc_clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE ydoc_clients FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON ydoc_clients USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
ALTER TABLE group_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE group_members FORCE ROW LEVEL SECURITY;
CREATE POLICY kmdn_org ON group_members USING (kmdn_org_visible(org_id)) WITH CHECK (kmdn_org_visible(org_id));
-- +end
