/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppOwnerRepoRouteRouteImport } from './routes/_app/$owner/$repo/route'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings/profile'
import { Route as AppOwnerRepoIndexRouteImport } from './routes/_app/$owner/$repo/index'
import { Route as AppOwnerRepoSplatRouteImport } from './routes/_app/$owner/$repo/$'
import { Route as AppOwnerRepoSettingsRouteImport } from './routes/_app/$owner/$repo/settings'
import { Route as AppOwnerRepoRevisionsIndexRouteImport } from './routes/_app/$owner/$repo/revisions/index'
import { Route as AppOwnerRepoRevisionsNumberRouteImport } from './routes/_app/$owner/$repo/revisions/$number'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOwnerRepoRouteRoute = AppOwnerRepoRouteRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnerRepoIndexRoute = AppOwnerRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOwnerRepoRouteRoute,
} as any)
const AppOwnerRepoSplatRoute = AppOwnerRepoSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppOwnerRepoRouteRoute,
} as any)
const AppOwnerRepoSettingsRoute = AppOwnerRepoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppOwnerRepoRouteRoute,
} as any)
const AppOwnerRepoRevisionsIndexRoute =
  AppOwnerRepoRevisionsIndexRouteImport.update({
    id: '/revisions/',
    path: '/revisions/',
    getParentRoute: () => AppOwnerRepoRouteRoute,
  } as any)
const AppOwnerRepoRevisionsNumberRoute =
  AppOwnerRepoRevisionsNumberRouteImport.update({
    id: '/revisions/$number',
    path: '/revisions/$number',
    getParentRoute: () => AppOwnerRepoRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/setup': typeof SetupRoute
  '/signin': typeof SigninRoute
  '/admin': typeof AppAdminRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/invite/$token': typeof InviteTokenRoute
  '/$owner/$repo': typeof AppOwnerRepoRouteRouteWithChildren
  '/settings/profile': typeof AppSettingsProfileRoute
  '/$owner/$repo/$': typeof AppOwnerRepoSplatRoute
  '/$owner/$repo/settings': typeof AppOwnerRepoSettingsRoute
  '/$owner/$repo/': typeof AppOwnerRepoIndexRoute
  '/$owner/$repo/revisions/$number': typeof AppOwnerRepoRevisionsNumberRoute
  '/$owner/$repo/revisions/': typeof AppOwnerRepoRevisionsIndexRoute
}
export interface FileRoutesByTo {
  '/setup': typeof SetupRoute
  '/signin': typeof SigninRoute
  '/admin': typeof AppAdminRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/invite/$token': typeof InviteTokenRoute
  '/': typeof AppIndexRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/$owner/$repo/$': typeof AppOwnerRepoSplatRoute
  '/$owner/$repo/settings': typeof AppOwnerRepoSettingsRoute
  '/$owner/$repo': typeof AppOwnerRepoIndexRoute
  '/$owner/$repo/revisions/$number': typeof AppOwnerRepoRevisionsNumberRoute
  '/$owner/$repo/revisions': typeof AppOwnerRepoRevisionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/setup': typeof SetupRoute
  '/signin': typeof SigninRoute
  '/_app/admin': typeof AppAdminRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$owner/$repo': typeof AppOwnerRepoRouteRouteWithChildren
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/$owner/$repo/$': typeof AppOwnerRepoSplatRoute
  '/_app/$owner/$repo/settings': typeof AppOwnerRepoSettingsRoute
  '/_app/$owner/$repo/': typeof AppOwnerRepoIndexRoute
  '/_app/$owner/$repo/revisions/$number': typeof AppOwnerRepoRevisionsNumberRoute
  '/_app/$owner/$repo/revisions/': typeof AppOwnerRepoRevisionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/signin'
    | '/admin'
    | '/auth/verify'
    | '/invite/$token'
    | '/$owner/$repo'
    | '/settings/profile'
    | '/$owner/$repo/$'
    | '/$owner/$repo/settings'
    | '/$owner/$repo/'
    | '/$owner/$repo/revisions/$number'
    | '/$owner/$repo/revisions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup'
    | '/signin'
    | '/admin'
    | '/auth/verify'
    | '/invite/$token'
    | '/'
    | '/settings/profile'
    | '/$owner/$repo/$'
    | '/$owner/$repo/settings'
    | '/$owner/$repo'
    | '/$owner/$repo/revisions/$number'
    | '/$owner/$repo/revisions'
  id:
    | '__root__'
    | '/_app'
    | '/setup'
    | '/signin'
    | '/_app/admin'
    | '/auth/verify'
    | '/invite/$token'
    | '/_app/'
    | '/_app/$owner/$repo'
    | '/_app/settings/profile'
    | '/_app/$owner/$repo/$'
    | '/_app/$owner/$repo/settings'
    | '/_app/$owner/$repo/'
    | '/_app/$owner/$repo/revisions/$number'
    | '/_app/$owner/$repo/revisions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SetupRoute: typeof SetupRoute
  SigninRoute: typeof SigninRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$owner/$repo': {
      id: '/_app/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof AppOwnerRepoRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$owner/$repo/': {
      id: '/_app/$owner/$repo/'
      path: '/'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof AppOwnerRepoIndexRouteImport
      parentRoute: typeof AppOwnerRepoRouteRoute
    }
    '/_app/$owner/$repo/$': {
      id: '/_app/$owner/$repo/$'
      path: '/$'
      fullPath: '/$owner/$repo/$'
      preLoaderRoute: typeof AppOwnerRepoSplatRouteImport
      parentRoute: typeof AppOwnerRepoRouteRoute
    }
    '/_app/$owner/$repo/settings': {
      id: '/_app/$owner/$repo/settings'
      path: '/settings'
      fullPath: '/$owner/$repo/settings'
      preLoaderRoute: typeof AppOwnerRepoSettingsRouteImport
      parentRoute: typeof AppOwnerRepoRouteRoute
    }
    '/_app/$owner/$repo/revisions/': {
      id: '/_app/$owner/$repo/revisions/'
      path: '/revisions'
      fullPath: '/$owner/$repo/revisions/'
      preLoaderRoute: typeof AppOwnerRepoRevisionsIndexRouteImport
      parentRoute: typeof AppOwnerRepoRouteRoute
    }
    '/_app/$owner/$repo/revisions/$number': {
      id: '/_app/$owner/$repo/revisions/$number'
      path: '/revisions/$number'
      fullPath: '/$owner/$repo/revisions/$number'
      preLoaderRoute: typeof AppOwnerRepoRevisionsNumberRouteImport
      parentRoute: typeof AppOwnerRepoRouteRoute
    }
  }
}

interface AppOwnerRepoRouteRouteChildren {
  AppOwnerRepoSplatRoute: typeof AppOwnerRepoSplatRoute
  AppOwnerRepoSettingsRoute: typeof AppOwnerRepoSettingsRoute
  AppOwnerRepoIndexRoute: typeof AppOwnerRepoIndexRoute
  AppOwnerRepoRevisionsNumberRoute: typeof AppOwnerRepoRevisionsNumberRoute
  AppOwnerRepoRevisionsIndexRoute: typeof AppOwnerRepoRevisionsIndexRoute
}

const AppOwnerRepoRouteRouteChildren: AppOwnerRepoRouteRouteChildren = {
  AppOwnerRepoSplatRoute: AppOwnerRepoSplatRoute,
  AppOwnerRepoSettingsRoute: AppOwnerRepoSettingsRoute,
  AppOwnerRepoIndexRoute: AppOwnerRepoIndexRoute,
  AppOwnerRepoRevisionsNumberRoute: AppOwnerRepoRevisionsNumberRoute,
  AppOwnerRepoRevisionsIndexRoute: AppOwnerRepoRevisionsIndexRoute,
}

const AppOwnerRepoRouteRouteWithChildren =
  AppOwnerRepoRouteRoute._addFileChildren(AppOwnerRepoRouteRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOwnerRepoRouteRoute: typeof AppOwnerRepoRouteRouteWithChildren
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppIndexRoute: AppIndexRoute,
  AppOwnerRepoRouteRoute: AppOwnerRepoRouteRouteWithChildren,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SetupRoute: SetupRoute,
  SigninRoute: SigninRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
