/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppOrgRouteRouteImport } from './routes/_app/$org/route'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppOrgIndexRouteImport } from './routes/_app/$org/index'
import { Route as AppOrgAdminRouteImport } from './routes/_app/$org/admin'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings/profile'
import { Route as AppOrgOwnerRepoRouteRouteImport } from './routes/_app/$org/$owner/$repo/route'
import { Route as AppOrgOwnerRepoIndexRouteImport } from './routes/_app/$org/$owner/$repo/index'
import { Route as AppOrgOwnerRepoSplatRouteImport } from './routes/_app/$org/$owner/$repo/$'
import { Route as AppOrgOwnerRepoConsistencyRouteImport } from './routes/_app/$org/$owner/$repo/consistency'
import { Route as AppOrgOwnerRepoGraphRouteImport } from './routes/_app/$org/$owner/$repo/graph'
import { Route as AppOrgOwnerRepoSettingsRouteImport } from './routes/_app/$org/$owner/$repo/settings'
import { Route as AppOrgOwnerRepoRevisionsIndexRouteImport } from './routes/_app/$org/$owner/$repo/revisions/index'
import { Route as AppOrgOwnerRepoRevisionsNumberRouteImport } from './routes/_app/$org/$owner/$repo/revisions/$number'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgRouteRoute = AppOrgRouteRouteImport.update({
  id: '/$org',
  path: '/$org',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgIndexRoute = AppOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgRouteRoute,
} as any)
const AppOrgAdminRoute = AppOrgAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppOrgRouteRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgOwnerRepoRouteRoute = AppOrgOwnerRepoRouteRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => AppOrgRouteRoute,
} as any)
const AppOrgOwnerRepoIndexRoute = AppOrgOwnerRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgOwnerRepoRouteRoute,
} as any)
const AppOrgOwnerRepoSplatRoute = AppOrgOwnerRepoSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppOrgOwnerRepoRouteRoute,
} as any)
const AppOrgOwnerRepoConsistencyRoute =
  AppOrgOwnerRepoConsistencyRouteImport.update({
    id: '/consistency',
    path: '/consistency',
    getParentRoute: () => AppOrgOwnerRepoRouteRoute,
  } as any)
const AppOrgOwnerRepoGraphRoute = AppOrgOwnerRepoGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppOrgOwnerRepoRouteRoute,
} as any)
const AppOrgOwnerRepoSettingsRoute = AppOrgOwnerRepoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppOrgOwnerRepoRouteRoute,
} as any)
const AppOrgOwnerRepoRevisionsIndexRoute =
  AppOrgOwnerRepoRevisionsIndexRouteImport.update({
    id: '/revisions/',
    path: '/revisions/',
    getParentRoute: () => AppOrgOwnerRepoRouteRoute,
  } as any)
const AppOrgOwnerRepoRevisionsNumberRoute =
  AppOrgOwnerRepoRevisionsNumberRouteImport.update({
    id: '/revisions/$number',
    path: '/revisions/$number',
    getParentRoute: () => AppOrgOwnerRepoRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/setup': typeof SetupRoute
  '/signin': typeof SigninRoute
  '/$org': typeof AppOrgRouteRouteWithChildren
  '/admin': typeof AppAdminRoute
  '/inbox': typeof AppInboxRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/invite/$token': typeof InviteTokenRoute
  '/$org/admin': typeof AppOrgAdminRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/$org/': typeof AppOrgIndexRoute
  '/$org/$owner/$repo': typeof AppOrgOwnerRepoRouteRouteWithChildren
  '/$org/$owner/$repo/$': typeof AppOrgOwnerRepoSplatRoute
  '/$org/$owner/$repo/consistency': typeof AppOrgOwnerRepoConsistencyRoute
  '/$org/$owner/$repo/graph': typeof AppOrgOwnerRepoGraphRoute
  '/$org/$owner/$repo/settings': typeof AppOrgOwnerRepoSettingsRoute
  '/$org/$owner/$repo/': typeof AppOrgOwnerRepoIndexRoute
  '/$org/$owner/$repo/revisions/$number': typeof AppOrgOwnerRepoRevisionsNumberRoute
  '/$org/$owner/$repo/revisions/': typeof AppOrgOwnerRepoRevisionsIndexRoute
}
export interface FileRoutesByTo {
  '/setup': typeof SetupRoute
  '/signin': typeof SigninRoute
  '/admin': typeof AppAdminRoute
  '/inbox': typeof AppInboxRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/invite/$token': typeof InviteTokenRoute
  '/': typeof AppIndexRoute
  '/$org/admin': typeof AppOrgAdminRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/$org': typeof AppOrgIndexRoute
  '/$org/$owner/$repo/$': typeof AppOrgOwnerRepoSplatRoute
  '/$org/$owner/$repo/consistency': typeof AppOrgOwnerRepoConsistencyRoute
  '/$org/$owner/$repo/graph': typeof AppOrgOwnerRepoGraphRoute
  '/$org/$owner/$repo/settings': typeof AppOrgOwnerRepoSettingsRoute
  '/$org/$owner/$repo': typeof AppOrgOwnerRepoIndexRoute
  '/$org/$owner/$repo/revisions/$number': typeof AppOrgOwnerRepoRevisionsNumberRoute
  '/$org/$owner/$repo/revisions': typeof AppOrgOwnerRepoRevisionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/setup': typeof SetupRoute
  '/signin': typeof SigninRoute
  '/_app/$org': typeof AppOrgRouteRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/inbox': typeof AppInboxRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$org/admin': typeof AppOrgAdminRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/$org/': typeof AppOrgIndexRoute
  '/_app/$org/$owner/$repo': typeof AppOrgOwnerRepoRouteRouteWithChildren
  '/_app/$org/$owner/$repo/$': typeof AppOrgOwnerRepoSplatRoute
  '/_app/$org/$owner/$repo/consistency': typeof AppOrgOwnerRepoConsistencyRoute
  '/_app/$org/$owner/$repo/graph': typeof AppOrgOwnerRepoGraphRoute
  '/_app/$org/$owner/$repo/settings': typeof AppOrgOwnerRepoSettingsRoute
  '/_app/$org/$owner/$repo/': typeof AppOrgOwnerRepoIndexRoute
  '/_app/$org/$owner/$repo/revisions/$number': typeof AppOrgOwnerRepoRevisionsNumberRoute
  '/_app/$org/$owner/$repo/revisions/': typeof AppOrgOwnerRepoRevisionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/signin'
    | '/$org'
    | '/admin'
    | '/inbox'
    | '/auth/verify'
    | '/invite/$token'
    | '/$org/admin'
    | '/settings/profile'
    | '/$org/'
    | '/$org/$owner/$repo'
    | '/$org/$owner/$repo/$'
    | '/$org/$owner/$repo/consistency'
    | '/$org/$owner/$repo/graph'
    | '/$org/$owner/$repo/settings'
    | '/$org/$owner/$repo/'
    | '/$org/$owner/$repo/revisions/$number'
    | '/$org/$owner/$repo/revisions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup'
    | '/signin'
    | '/admin'
    | '/inbox'
    | '/auth/verify'
    | '/invite/$token'
    | '/'
    | '/$org/admin'
    | '/settings/profile'
    | '/$org'
    | '/$org/$owner/$repo/$'
    | '/$org/$owner/$repo/consistency'
    | '/$org/$owner/$repo/graph'
    | '/$org/$owner/$repo/settings'
    | '/$org/$owner/$repo'
    | '/$org/$owner/$repo/revisions/$number'
    | '/$org/$owner/$repo/revisions'
  id:
    | '__root__'
    | '/_app'
    | '/setup'
    | '/signin'
    | '/_app/$org'
    | '/_app/admin'
    | '/_app/inbox'
    | '/auth/verify'
    | '/invite/$token'
    | '/_app/'
    | '/_app/$org/admin'
    | '/_app/settings/profile'
    | '/_app/$org/'
    | '/_app/$org/$owner/$repo'
    | '/_app/$org/$owner/$repo/$'
    | '/_app/$org/$owner/$repo/consistency'
    | '/_app/$org/$owner/$repo/graph'
    | '/_app/$org/$owner/$repo/settings'
    | '/_app/$org/$owner/$repo/'
    | '/_app/$org/$owner/$repo/revisions/$number'
    | '/_app/$org/$owner/$repo/revisions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SetupRoute: typeof SetupRoute
  SigninRoute: typeof SigninRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$org': {
      id: '/_app/$org'
      path: '/$org'
      fullPath: '/$org'
      preLoaderRoute: typeof AppOrgRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$org/': {
      id: '/_app/$org/'
      path: '/'
      fullPath: '/$org/'
      preLoaderRoute: typeof AppOrgIndexRouteImport
      parentRoute: typeof AppOrgRouteRoute
    }
    '/_app/$org/admin': {
      id: '/_app/$org/admin'
      path: '/admin'
      fullPath: '/$org/admin'
      preLoaderRoute: typeof AppOrgAdminRouteImport
      parentRoute: typeof AppOrgRouteRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$org/$owner/$repo': {
      id: '/_app/$org/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/$org/$owner/$repo'
      preLoaderRoute: typeof AppOrgOwnerRepoRouteRouteImport
      parentRoute: typeof AppOrgRouteRoute
    }
    '/_app/$org/$owner/$repo/': {
      id: '/_app/$org/$owner/$repo/'
      path: '/'
      fullPath: '/$org/$owner/$repo/'
      preLoaderRoute: typeof AppOrgOwnerRepoIndexRouteImport
      parentRoute: typeof AppOrgOwnerRepoRouteRoute
    }
    '/_app/$org/$owner/$repo/$': {
      id: '/_app/$org/$owner/$repo/$'
      path: '/$'
      fullPath: '/$org/$owner/$repo/$'
      preLoaderRoute: typeof AppOrgOwnerRepoSplatRouteImport
      parentRoute: typeof AppOrgOwnerRepoRouteRoute
    }
    '/_app/$org/$owner/$repo/consistency': {
      id: '/_app/$org/$owner/$repo/consistency'
      path: '/consistency'
      fullPath: '/$org/$owner/$repo/consistency'
      preLoaderRoute: typeof AppOrgOwnerRepoConsistencyRouteImport
      parentRoute: typeof AppOrgOwnerRepoRouteRoute
    }
    '/_app/$org/$owner/$repo/graph': {
      id: '/_app/$org/$owner/$repo/graph'
      path: '/graph'
      fullPath: '/$org/$owner/$repo/graph'
      preLoaderRoute: typeof AppOrgOwnerRepoGraphRouteImport
      parentRoute: typeof AppOrgOwnerRepoRouteRoute
    }
    '/_app/$org/$owner/$repo/settings': {
      id: '/_app/$org/$owner/$repo/settings'
      path: '/settings'
      fullPath: '/$org/$owner/$repo/settings'
      preLoaderRoute: typeof AppOrgOwnerRepoSettingsRouteImport
      parentRoute: typeof AppOrgOwnerRepoRouteRoute
    }
    '/_app/$org/$owner/$repo/revisions/': {
      id: '/_app/$org/$owner/$repo/revisions/'
      path: '/revisions'
      fullPath: '/$org/$owner/$repo/revisions/'
      preLoaderRoute: typeof AppOrgOwnerRepoRevisionsIndexRouteImport
      parentRoute: typeof AppOrgOwnerRepoRouteRoute
    }
    '/_app/$org/$owner/$repo/revisions/$number': {
      id: '/_app/$org/$owner/$repo/revisions/$number'
      path: '/revisions/$number'
      fullPath: '/$org/$owner/$repo/revisions/$number'
      preLoaderRoute: typeof AppOrgOwnerRepoRevisionsNumberRouteImport
      parentRoute: typeof AppOrgOwnerRepoRouteRoute
    }
  }
}

interface AppOrgOwnerRepoRouteRouteChildren {
  AppOrgOwnerRepoSplatRoute: typeof AppOrgOwnerRepoSplatRoute
  AppOrgOwnerRepoConsistencyRoute: typeof AppOrgOwnerRepoConsistencyRoute
  AppOrgOwnerRepoGraphRoute: typeof AppOrgOwnerRepoGraphRoute
  AppOrgOwnerRepoSettingsRoute: typeof AppOrgOwnerRepoSettingsRoute
  AppOrgOwnerRepoIndexRoute: typeof AppOrgOwnerRepoIndexRoute
  AppOrgOwnerRepoRevisionsNumberRoute: typeof AppOrgOwnerRepoRevisionsNumberRoute
  AppOrgOwnerRepoRevisionsIndexRoute: typeof AppOrgOwnerRepoRevisionsIndexRoute
}

const AppOrgOwnerRepoRouteRouteChildren: AppOrgOwnerRepoRouteRouteChildren = {
  AppOrgOwnerRepoSplatRoute: AppOrgOwnerRepoSplatRoute,
  AppOrgOwnerRepoConsistencyRoute: AppOrgOwnerRepoConsistencyRoute,
  AppOrgOwnerRepoGraphRoute: AppOrgOwnerRepoGraphRoute,
  AppOrgOwnerRepoSettingsRoute: AppOrgOwnerRepoSettingsRoute,
  AppOrgOwnerRepoIndexRoute: AppOrgOwnerRepoIndexRoute,
  AppOrgOwnerRepoRevisionsNumberRoute: AppOrgOwnerRepoRevisionsNumberRoute,
  AppOrgOwnerRepoRevisionsIndexRoute: AppOrgOwnerRepoRevisionsIndexRoute,
}

const AppOrgOwnerRepoRouteRouteWithChildren =
  AppOrgOwnerRepoRouteRoute._addFileChildren(AppOrgOwnerRepoRouteRouteChildren)

interface AppOrgRouteRouteChildren {
  AppOrgAdminRoute: typeof AppOrgAdminRoute
  AppOrgIndexRoute: typeof AppOrgIndexRoute
  AppOrgOwnerRepoRouteRoute: typeof AppOrgOwnerRepoRouteRouteWithChildren
}

const AppOrgRouteRouteChildren: AppOrgRouteRouteChildren = {
  AppOrgAdminRoute: AppOrgAdminRoute,
  AppOrgIndexRoute: AppOrgIndexRoute,
  AppOrgOwnerRepoRouteRoute: AppOrgOwnerRepoRouteRouteWithChildren,
}

const AppOrgRouteRouteWithChildren = AppOrgRouteRoute._addFileChildren(
  AppOrgRouteRouteChildren,
)

interface AppRouteChildren {
  AppOrgRouteRoute: typeof AppOrgRouteRouteWithChildren
  AppAdminRoute: typeof AppAdminRoute
  AppInboxRoute: typeof AppInboxRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOrgRouteRoute: AppOrgRouteRouteWithChildren,
  AppAdminRoute: AppAdminRoute,
  AppInboxRoute: AppInboxRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SetupRoute: SetupRoute,
  SigninRoute: SigninRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
